sudo: required
language: python
dist: xenial
python: '3.5'

services:
  - docker

install:
  - source .env
  - pip install pipenv
  - pipenv sync --dev

script: pytest

before_deploy:
  docker login -u ${DOCKER_USER} -p ${DOCKER_PASSWORD};
  export TAG_VERSION=$(git describe --tags);
  bash ./build-docker.sh;

deploy:
  # Deploy images with tag branch name on any non-tagged push to an upstream branch
  - provider: script
    script: bash ./push-docker.sh
    skip_cleanup: true
    on:
      tags: false
      repo: ${GITHUB_REPO}
      all_branches: true

  # Deploy images tagged with git tag on tagged commits
  - provider: script
    script: 
      bash ./push-docker.sh ${TAG_VERSION};
      bash ./push-docker.sh newest-tag;
    skip_cleanup: true
    on:
      tags: true
      repo: ${GITHUB_REPO}
