pool:
  vmImage: 'Ubuntu-16.04'

variables:
  # Variables imported from brewblox group:
  # DOCKER_USER
  # DOCKER_PASSWORD
  # PYPI_USER
  # PYPI_PASSWORD
  - group: brewblox

steps:
- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.5'
    architecture: 'x64'

- bash: |
    BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    TAG=$(git describe --tags | grep "^[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]$")
    echo "##vso[task.setvariable variable=brewblox.branch]$BRANCH"
    echo "##vso[task.setvariable variable=brewblox.tag]$TAG"
  displayName: export build variables

- bash: |
    pip install pipenv
    pipenv install --system --dev --deploy
    pytest
  displayName: Run Pytest

- bash: |
    echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
  displayName: Docker login
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- bash: |
    bash ./build-docker.sh
  displayName: Build docker containers

- bash: |
    bash ./push-docker.sh $(brewblox.tag)
    bash ./push-docker.sh newest-tag
  displayName: Deploy newest-tag and version tag to Docker Hub on tagged commits
  condition: and(succeeded(), variables['brewblox.tag'])

- bash: |
    bash ./docker.sh
  displayName: Deploy branch to Docker Hub on any push to the GitHub repository
  condition: and(succeeded(), variables['brewblox.branch'], not(variables['brewblox.tag']))
  env:
  # the script looks for $TRAVIS_BRANCH to determine branch tag
    TRAVIS_BRANCH: $(brewblox.branch)
