pool:
  vmImage: 'Ubuntu-20.04'

trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - refs/heads/*

variables:
  # Variables imported from brewblox group:
  # DOCKER_USER
  # DOCKER_PASSWORD
  - group: brewblox

pr:
  branches:
    include:
      - '*'

steps:
- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.5'
    architecture: 'x64'

- bash: |
    set -o allexport; source .env; set +o allexport
    echo "##vso[task.setvariable variable=DOCKER_REPO]$DOCKER_REPO"
  displayName: Export .env variables

- bash: |
    BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    TAG=$(echo $BRANCH | tr '/' '-' | tr '[:upper:]' '[:lower:]')
    echo "##vso[task.setvariable variable=BRANCH]$BRANCH"
    echo "##vso[task.setvariable variable=TAG]$TAG"
  displayName: Export build variables

- bash: |
    pip install poetry
    poetry install
  displayName: Install dependencies

- bash: |
    poetry run pytest
  displayName: Run Pytest

- bash: echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
  displayName: Docker login
  condition: and(succeeded(), variables.BRANCH)

- bash: |
    bash docker/before_build.sh
  displayName: Run before_build.sh script
  condition: and(succeeded(), variables.BRANCH)
  
- bash: |
    docker build --tag $(DOCKER_REPO):$(TAG) docker
    docker push $(DOCKER_REPO):$(TAG)
  displayName: Deploy Docker images with branch tags
  condition: and(succeeded(), variables.BRANCH)
