pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - refs/heads/*

variables:
  # Variables imported from brewblox group:
  # DOCKER_USER
  # DOCKER_PASSWORD
  - group: brewblox

pr:
  branches:
    include:
      - '*'

steps:
- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.5'
    architecture: 'x64'

- bash: |
    RELEASE=$(git describe --tags | grep "^[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]$")
    BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    TAG=$(echo $BRANCH | tr '/' '-' | tr '[:upper:]' '[:lower:]')
    echo "##vso[task.setvariable variable=RELEASE]$RELEASE"
    echo "##vso[task.setvariable variable=BRANCH]$BRANCH"
    echo "##vso[task.setvariable variable=TAG]$TAG"
  displayName: Export build variables

- bash: |
    pip install pipenv
    pipenv install --system --dev --deploy
  displayName: Install packages

- bash: pytest
  displayName: Run Pytest

- bash: echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
  displayName: Docker login
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- bash: bash ./build-docker.sh
  displayName: Build Docker images
  
- bash: |
    bash ./push-docker.sh $(TAG)
  displayName: Deploy Docker images with branch tags
  condition: and(succeeded(), variables['BRANCH'], not(variables['RELEASE']))

- bash: |
    bash ./push-docker.sh $(RELEASE)
    bash ./push-docker.sh newest-tag
  displayName: Deploy Docker images with release tags
  condition: and(succeeded(), variables['RELEASE'])
