pool:
  vmImage: 'Ubuntu-18.04'

trigger:
  tags:
    include:
      - "*"
  branches:
    include:
      - refs/heads/*

variables:
  # Variables imported from brewblox group:
  # DOCKER_USER
  # DOCKER_PASSWORD
  - group: brewblox

pr:
  branches:
    include:
      - '*'

steps:
- task: UsePythonVersion@0
  inputs:
    addToPath: true
    versionSpec: '3.5'
    architecture: 'x64'

- bash: |
    set -o allexport; source .env; set +o allexport
    echo "##vso[task.setvariable variable=DOCKER_REPO]$DOCKER_REPO"
  displayName: Export .env variables

- bash: |
    RELEASE=$(git describe --tags | grep "^[[:digit:]]*\.[[:digit:]]*\.[[:digit:]]$")
    BRANCH=$(echo $(Build.SourceBranch) | grep -oP "^refs/heads/\K.*")
    TAG=$(echo $BRANCH | tr '/' '-' | tr '[:upper:]' '[:lower:]')
    echo "##vso[task.setvariable variable=RELEASE]$RELEASE"
    echo "##vso[task.setvariable variable=BRANCH]$BRANCH"
    echo "##vso[task.setvariable variable=TAG]$TAG"
  displayName: Export build variables

- bash: |
    pip install poetry
    poetry install
  displayName: Install dependencies

- bash: poetry run pytest
  displayName: Run Pytest

- bash: echo $(DOCKER_PASSWORD) | docker login -u $(DOCKER_USER) --password-stdin
  displayName: Docker login
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))

- bash: bash ./before_build.sh
  displayName: Run before_build.sh script
  workingDirectory: docker
  condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
  
- bash: >-
    docker build
    --tag $(DOCKER_REPO):$(TAG)
    --push
    docker
  displayName: Deploy Docker images with branch tags
  condition: and(succeeded(), variables['BRANCH'], not(variables['RELEASE']))

- bash: >-
    docker build
    --tag $(DOCKER_REPO):$(RELEASE)
    --tag $(DOCKER_REPO):newest-tag
    --push
    docker
  displayName: Deploy Docker images with release tags
  condition: and(succeeded(), variables['RELEASE'])
